### ISSUE TITLE
The Midnight Commander becomes broken after opening in new terminal tab

### ISSUE THREAD

**Issue by SkorikSergey** [codenvy/codenvy#1836]
**Reproduction Steps:**

1. Start any workspace which has the Midnight Commander
2. Create a new terminal
3. Start the Midnight Commander
4. The Midnight Commander window is broken

**Server location:** nightly.codenvy-stg.com, nightly-onprem.codenvy-stg.com

**Codenvy cli.log output:**  
![selection_011](https://cloud.githubusercontent.com/assets/7760565/23301755/243f5778-fa94-11e6-8b41-e0e7b895533d.png)

![terminal_bugs](https://cloud.githubusercontent.com/assets/7760565/23301756/2721c070-fa94-11e6-8f6e-cd070458cb96.gif)

**Comment by AndrienkoAleksandr** [comment]
This bug fixed https://github.com/sourcelair/xterm.js/issues/385 in the newer version of xterm.js

**Comment by AndrienkoAleksandr** [comment]
depends on https://github.com/eclipse/che/issues/4251

**Comment by SkorikSergey** [comment]
This bug is fixed.

**Comment by SkorikSergey** [comment]
Still actual for nightly.codenvy-stg.com, nightly-onprem.codenvy-stg.com.

**Comment by SkorikSergey** [comment]
Still actual for nightly.codenvy-stg.com, nightly-onprem.codenvy-stg.com.

**Comment by AndrienkoAleksandr** [comment]
Is this still actual? This should be fixed after https://github.com/eclipse/che-lib/pull/24 https://github.com/eclipse/che/pull/4449

**Comment by SkorikSergey** [comment]
This bug is still actual.
![anim](https://cloud.githubusercontent.com/assets/7760565/25275233/de1b19b4-269c-11e7-92a0-c6c4a7efdc1e.gif)

**Comment by AndrienkoAleksandr** [comment]
Yes, @SkorikSergey  this bug is actual, but can be reproducible only on the remote server like nightly... One of the reason of this bug was fixed after update terminal to the latest version 2.4.0, but seems some another problem is still exists and it can't be reproducable locally. So I will occupate some remote test server and try to fix this bug.
